Repository skypilot-dev/skypilot-site, pull requests merged in 2020-03, with the labels that each got.

#1 Configure tooling
  .editorconfig
  .eslintignore
  .eslintrc.js
  .github/workflows/node-check-code.yaml
  .github/workflows/node-prerelease.yaml
  .github/workflows/node-stable-release.yaml
  .gitignore
  .huskyrc.js
  .lintstagedrc.js
  .nvmrc
  .skypilot/quick-release.yaml
  babel.config.js
  jest.config.js
  jest.integration.config.js
  jest.standalone.config.js
  package.json
  src/__tests__/index.app.test.ts
  src/index.ts
  src/scripts/.eslintrc.js
  tsconfig.generate-typings.json
  tsconfig.json
  yarn.lock
Labels: refactor

#2 Add basic HTML structure
  public/index.html
  public/main.css
  public/vendors/css/grid.css
  public/vendors/css/normalize.css
Labels: enhancement

#3 Reformat HTML & CSS files
  public/index.html
  public/main.css
  public/vendors/css/grid.css
Labels: refactor

#4 Add initial landing-page content: hero message & services
  public/index.html
Labels: enhancement

#5 Add more basic html structure to landing page
  public/index.html
Labels: enhancement

#6 Add content to landing page
  public/index.html
Labels: enhancement

#9 Upgrade Toolchain
  package.json
  yarn.lock
Labels: tooling

#8 Add more content to landing page
  public/index.html
Labels: enhancement

#11 Add layout and styling to header, services, highlights & team sections
  public/index.html
  public/main.css
Labels: enhancement

#12 Finish layout and spacing for process section
  public/index.html
  public/main.css
Labels: enhancement

#13 Upgrade Toolchain package
  .eslintignore
  .gitignore
  package.json
  yarn.lock
Labels: refactor

#14 Modify website for tablet responsive break points (947px - 1186px)
  public/index.html
  public/main.css
  public/queries.css
Labels: enhancement

#15 Resize wordmark to match logo
  public/main.css
Labels: enhancement

#17 Modify sections up until contact for 480-767px responsive break point
  public/index.html
  public/main.css
  public/queries.css
Labels: enhancement

#16 Improve landing-page copy
  public/index.html
Labels: enhancement

#18 Final responsive minor breakpoints added
  public/index.html
  public/main.css
  public/queries.css
Labels: enhancement

#20 Watch only public files when running local server
  package.json
Labels: tooling
